### ISSUE TITLE
I want  to know how Flyingdog in photoshop uses Gyre to get to the model person position, because I want to use other models

### ISSUE THREAD

**Issue by guangxinzhao** [stablecabal/gyre-installer#1]
Helo,I would like to know the model location of Gyre-installer

**Comment by hafriedlander** [comment]
Hello.

The models are installed in your home directory, inside a ".cache\huggingface\hub" folder.

There's a bunch of additional models pre-configured but disabled. To enable, edit your config file and add the line: SD_ENABLE_ENGINE_1={the_id}. For instance, to enable Realistic Vision 2.0, add SD_ENABLE_ENGINE_1=realistic-vision-v2-0 (use _2, _3, etc for more models). They will be downloaded automatically.

You can look in gyreconfig\extras to see the available models, and you can duplicate one of those and edit it to add other models. There's examples of different types in there (Civitai, HuggingFace, etc).
