### ISSUE TITLE
Changing the cache directory

### ISSUE THREAD

**Issue by AlonAshken** [stablecabal/gyre-installer#4]
The run.cmd decided that the cache directory should be on my C drive which caused all the storage to run out there.
I want to specify where the cache directory is (it is already downloaded but I moved it).
How can I do that?

**Comment by hafriedlander** [comment]
Add `XDG_CACHE_PATH={the path}` as a new line in your config file (not config.dist) after running install_or_update.cmd but before running run.cmd. For instance `XDG_CACHE_PATH=e:/gyrecache`.

**Comment by AlonAshken** [comment]
Thanks, it worked!
