### ISSUE TITLE
always using gpu0

### ISSUE THREAD

**Issue by lilei105** [stablecabal/gyre-installer#5]
Thanks a million guys, I love this project. I'm running on my dual-gpu laptop. Turns out pytorch always finds gpu0, which is the very weak built-in one, thus it throws CUDA out of memory error when trying inpainting. Full logs below:

D:\Software\gyre-installer>run.cmd
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
gyre.cache         | Cache disk folder: C:\Users\lilei\.cache\gyre\resource_cache
gyre.server        | Xformers defaults to on
gyre.engines_yaml  | (vram4) False
gyre.server        | Manager loaded
gyre.server        | GRPC listening on port 50051, HTTP listening on port 5000. Start your engines....
gyre.manager       | Loading engines...
gyre.manager       |   - Engine hinters-hed...
gyre.manager       |     - Model hinters-hed...
gyre.manager       |   - Engine hinters-lineart-anime...
gyre.manager       |     - Model hinters-lineart-anime...
gyre.manager       |   - Engine hinters-lineart-contour...
gyre.manager       |     - Model hinters-lineart-contour...
gyre.manager       |   - Engine hinters-lineart-opensketch...
gyre.manager       |     - Model hinters-lineart-opensketch...
gyre.manager       |   - Engine hinters-uniformer...
gyre.manager       |     - Model hinters-uniformer-small...
gyre.pipeline.hint | Use Checkpoint: False
gyre.pipeline.hint | Checkpoint Number: [0, 0, 0, 0]
gyre.pipeline.hint | Use global window for all blocks in stage3
py.warnings        | D:\Software\gyre-installer\gyre\gyre\src\mmsegmentation\mmseg\models\losses\cross_entropy_loss.py:235: UserWarning: Default ``avg_non_ignore`` is False, if you would like to ignore the certain label and average loss over non-ignore labels, which is the same with PyTorch official cross_entropy, set ``avg_non_ignore=True``.
  warnings.warn(

gyre.manager       |   - Engine hinters-pose...
gyre.manager       |     - Model hinters-keypose-detector-x101...
gyre.manager       |     - Model hinters-keypose-posemodel-384...
gyre.manager       |   - Engine inspyrenet...
gyre.manager       |     - Model inspyrenet...
py.warnings        | D:\Software\gyre-installer\env\envs\gyre\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ..\aten\src\ATen\native\TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

gyre.manager       |   - Engine hinters-baenormal...
gyre.manager       |     - Model hinters-baenormal...
torch.hub          | Using cache found in C:\Users\lilei/.cache\torch\hub\rwightman_gen-efficientnet-pytorch_master
gyre.pipeline.hint | Loading base model ()...Done.
gyre.pipeline.hint | Removing last two layers (global_pool & classifier).
gyre.manager       |   - Engine depth-zoe-n...
gyre.manager       |     - Model zoe-n...
midas.model_loader | Model loaded, number of parameters = 344M
zoedepth.models.ba | Params passed to Resize transform:
zoedepth.models.ba |    width:  512
zoedepth.models.ba |    height:  384
zoedepth.models.ba |    resize_target:  True
zoedepth.models.ba |    keep_aspect_ratio:  True
zoedepth.models.ba |    ensure_multiple_of:  32
zoedepth.models.ba |    resize_method:  minimal
zoedepth.models.mo | Using pretrained resource local::C:\Users\lilei\.cache\huggingface\hub\models--halffried--gyre_zoedepth\snapshots\4f9a9b50c3f6c505b2098f252556989eea74b225\ZoeD_M12_N.safetensors
zoedepth.models.mo | Loaded successfully
gyre.manager       |   - Engine stable-diffusion-v1-5...
gyre.manager       |     - Model stable-diffusion-v1-5...
gyre.manager       |     - Model stable-diffusion-v1-5-base...
py.warnings        | D:\Software\gyre-installer\env\envs\gyre\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(

transformers.model | `text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
gyre.manager       |     - Model stability-vae-mse...
gyre.manager       |     - Model stable-diffusion-v1-5-inpaint...
gyre.manager       |     - Model clip-common...
gyre.manager       |     - Model laion-clip-h...
transformers.model | `text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
gyre.manager       |   - Hintset hintset-sd15-common...
gyre.manager       |     - Model coadapter-canny...
gyre.manager       |     - Model coadapter-fuser...
gyre.manager       |     - Model coadapter-color...
gyre.manager       |     - Model coadapter-depth...
gyre.manager       |     - Model coadapter-sketch...
gyre.manager       |     - Model coadapter-style...
gyre.manager       |     - Model openai-clip-l...
transformers.model | `text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
gyre.manager       |     - Model t2i-adapter-keypose...
gyre.manager       |     - Model t2i-adapter-openpose...
gyre.manager       |     - Model controlnet11-canny...
gyre.manager       |     - Model controlnet11-normalbae...
gyre.manager       |     - Model controlnet11-seg...
gyre.manager       |     - Model controlnet11-shuffle...
gyre.manager       |     - Model controlnet11-softedge...
gyre.manager       |   - Engine upscaler-x4...
gyre.manager       |     - Model upscaler-x4...
gyre.manager       |   - Engine hat-gan-x4...
gyre.manager       |     - Model hat-gan-x4...
gyre.server        | All engines ready, loading took 31.1s, total startup 32.5s
gyre.server        | Visit http://localhost:5000/ (or the web-accessible URL if you're running on a remote server) to access the Web UI
gyre.services.gene | Generating:
gyre.services.gene |   guidance_scale: 7.5
gyre.services.gene |   height: 512
gyre.services.gene |   hint_images: []
gyre.services.gene |   hires_fix: False
gyre.services.gene |   karras_rho: 9.0
gyre.services.gene |   num_images_per_prompt: 1
gyre.services.gene |   num_inference_steps: 15
gyre.services.gene |   prompt: Prompt(fragments=[PromptFragment(prompt='a dog barking at a cat, highly detailed', weight=1.0)], clip_layer=None)
gyre.services.gene |   sampler: 554
gyre.services.gene |   sigma_min: 0.10719999670982361
gyre.services.gene |   tiling: False
gyre.services.gene |   token_embeddings: []
gyre.services.gene |   width: 512
gyre.services.gene |   seed: [2708679783]
gyre.pipeline.unif | Mode tree:
gyre.pipeline.unif | - mode_class: Txt2imgMode
gyre.pipeline.unif |   hints: list, len 0
gyre.pipeline.unif |   depth_map: None
gyre.pipeline.unif |   unet: 4 channels
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:06<00:00,  2.30it/s]
gyre.services.gene | Generating:
gyre.services.gene |   guidance_scale: 7.5
gyre.services.gene |   height: 512
gyre.services.gene |   hint_images: []
gyre.services.gene |   hires_fix: False
gyre.services.gene |   karras_rho: 9.0
gyre.services.gene |   num_images_per_prompt: 1
gyre.services.gene |   num_inference_steps: 15
gyre.services.gene |   prompt: Prompt(fragments=[PromptFragment(prompt='a dog barking at a cat, highly detailed', weight=1.0)], clip_layer=None)
gyre.services.gene |   sampler: 554
gyre.services.gene |   sigma_min: 0.10719999670982361
gyre.services.gene |   tiling: False
gyre.services.gene |   token_embeddings: []
gyre.services.gene |   width: 512
gyre.services.gene |   seed: [2708679784]
gyre.pipeline.unif | Mode tree:
gyre.pipeline.unif | - mode_class: Txt2imgMode
gyre.pipeline.unif |   hints: list, len 0
gyre.pipeline.unif |   depth_map: None
gyre.pipeline.unif |   unet: 4 channels
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:02<00:00,  6.68it/s]
gyre.services.gene | Generating:
gyre.services.gene |   guidance_scale: 7.5
gyre.services.gene |   height: 512
gyre.services.gene |   hint_images: []
gyre.services.gene |   hires_fix: False
gyre.services.gene |   karras_rho: 9.0
gyre.services.gene |   num_images_per_prompt: 1
gyre.services.gene |   num_inference_steps: 15
gyre.services.gene |   prompt: Prompt(fragments=[PromptFragment(prompt='a dog barking at a cat, highly detailed', weight=1.0)], clip_layer=None)
gyre.services.gene |   sampler: 554
gyre.services.gene |   sigma_min: 0.10719999670982361
gyre.services.gene |   strength: 1.0
gyre.services.gene |   tiling: False
gyre.services.gene |   token_embeddings: []
gyre.services.gene |   width: 512
gyre.services.gene |   seed: [4206198504]
gyre.services.gene |   image: [Image at http://localhost:5000/log/0d882828-d2cf-4b09-8d74-4968a4b3b785]
gyre.services.gene |   mask_image: [Image at http://localhost:5000/log/f3f6e2f5-2964-41a2-a615-a1b28439fa29]
gyre.services.gene |   outmask_image: [Image at http://localhost:5000/log/42162d0e-a387-4754-baf2-d8b6bfaca8a7]
gyre.pipeline.unif | Mode tree:
gyre.pipeline.unif | - mode_class: EnhancedRunwayInpaintMode
gyre.pipeline.unif |   hints: list, len 0
gyre.pipeline.unif |   depth_map: None
gyre.pipeline.unif |   unet: 9 channels
gyre.services.exce | Exception in handler Generate. Traceback (most recent call last):
  File "D:\Software\gyre-installer\gyre\gyre\services\exception_to_grpc.py", line 45, in wrapper
    yield from func(*args, **kwargs)
  File "D:\Software\gyre-installer\gyre\gyre\services\generate.py", line 1073, in Generate
    results = engine(**batchargs, stop_event=stop_event)
  File "D:\Software\gyre-installer\gyre\gyre\pipeline\pipeline_wrapper.py", line 389, in __call__
    images = self._pipeline(**pipeline_args)
  File "D:\Software\gyre-installer\env\envs\gyre\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Software\gyre-installer\gyre\gyre\pipeline\unified_pipeline.py", line 2380, in __call__
    latents = mode_tree.initial_latents()
  File "D:\Software\gyre-installer\gyre\gyre\pipeline\unified_pipeline.py", line 1041, in initial_latents
    return self.root.initial_latents()
  File "D:\Software\gyre-installer\gyre\gyre\pipeline\unified_pipeline.py", line 1129, in initial_latents
    return self.mode.generateLatents()
  File "D:\Software\gyre-installer\gyre\gyre\pipeline\unified_pipeline.py", line 597, in generateLatents
    init_latents = self._buildInitialLatents()
  File "D:\Software\gyre-installer\gyre\gyre\pipeline\unified_pipeline.py", line 313, in _buildInitialLatents
    return self._convertToLatents(self.image)
  File "D:\Software\gyre-installer\gyre\gyre\pipeline\unified_pipeline.py", line 301, in _convertToLatents
    dist = self.pipeline.vae.encode(image).latent_dist
  File "D:\Software\gyre-installer\env\envs\gyre\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "D:\Software\gyre-installer\env\envs\gyre\lib\site-packages\diffusers\models\autoencoder_kl.py", line 164, in encode
    h = self.encoder(x)
  File "D:\Software\gyre-installer\env\envs\gyre\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Software\gyre-installer\env\envs\gyre\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\Software\gyre-installer\env\envs\gyre\lib\site-packages\diffusers\models\vae.py", line 129, in forward
    sample = down_block(sample)
  File "D:\Software\gyre-installer\env\envs\gyre\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Software\gyre-installer\env\envs\gyre\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\Software\gyre-installer\env\envs\gyre\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 1014, in forward
    hidden_states = resnet(hidden_states, temb=None)
  File "D:\Software\gyre-installer\env\envs\gyre\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Software\gyre-installer\env\envs\gyre\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "D:\Software\gyre-installer\env\envs\gyre\lib\site-packages\diffusers\models\resnet.py", line 599, in forward
    output_tensor = (input_tensor + hidden_states) / self.output_scale_factor
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 6.00 GiB total capacity; 3.84 GiB already allocated; 0 bytes free; 6.00 GiB allowed; 3.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by hafriedlander** [comment]
Hi,

Actually, Gyre will try and use all your CUDA devices by default. But it will start with device 0, which will immediately break if it's too low spec :).

You should be able to use the CUDA_VISIBLE_DEVICES environment variable (https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/) to hide any devices you want to avoid using. You might be able to put this in your `config` file, or you might have to use `set CUDA_VISIBLE_DEVICES=1` before running run.cmd (I don't have multiple GPUs, so it's hard for me to test). Please let me know if this works.

**Comment by hafriedlander** [comment]
I've tested this, and setting CUDA_VISIBLE_DEVICES (via `config` or environment variable) works. The latest version fixes the RAM monitor always monitoring CUDA device 0 (although that doesn't affect function, just annoying). There are no currently known issues with multi-GPU usage, but feel free to open a ticket if you're still having issues.
