### ISSUE TITLE
Error: "Bad state: StreamSink is already bound to a stream" in installing Gyre.

### ISSUE THREAD

**Issue by yoshisatose** [stablecabal/gyre-installer#6]
I was successful in installing Gyre (with GUI) on Windows by running install_or_update.cmd.
However, I encountered an error when I tried to install it on Ubuntu by running bash install_or_update.sh. 

```
$ bash install_or_update.sh
--------------------------------------
Creating or updating conda environment
--------------------------------------

Using system Conda at /home/myaccount/miniconda3/bin/conda
Environment doesn't exist. Creating.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

Downloading and Extracting Packages

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate /path/to/gyre-installer/condaenv
#
# To deactivate an active environment, use
#
#     $ conda deactivate


--------------------------------------
Run main install script
--------------------------------------

Unhandled exception:
Bad state: StreamSink is already bound to a stream
#0      _StreamSinkImpl.addStream (dart:io/io_sink.dart:148)
#1      _StdSink.addStream (dart:io/stdio.dart:361)
#2      main (file:///home/hfried/work/gyre-installer/src/install_or_update.dart:93)
<asynchronous suspension>
```

**Comment by hafriedlander** [comment]
Hi,

Interesting, I will look into this. Thanks.

Can you test whether it works using the internal micromamba? (Remove the "CONDA_EXE" environment variable before running install_or_update.sh, or set it to a file that does not exist, like `CONDA_EXE=none bash install_or_update.sh`).

**Comment by aniketgore** [comment]
Receiving the same error while installing on the ubuntu using the bundle install.
Tried using CONDA_EXE=none bash install_or_update.sh, but not it aborts at a later stage:

--------------------------------------
Run main install script
--------------------------------------

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
 
----Error--------------------------
Whoops - something went wrong. Aborting.

**Comment by yoshisatose** [comment]
Hi, @hafriedlander !
Thank you for your quick response and sorry for my late reply. 
`CONDA_EXE=none bash install_or_update.sh` worked fine for me. I've now managed to install both the "server"-version and the "GUI"-version (bundle) on Ubuntu 2022_04.
Thanks a lot!

**Comment by hafriedlander** [comment]
Closing as this specific issue is solved by the workaround above. The newest version of the installer asks whether to use the system conda or micromamba, so it's even easier to work around.

@aniketgore if you still haven't resolved your install issue (and you still want to), please try a fresh install, and open a new bug if you're still getting that other error.
